resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- env.yaml
- manager_webhook_patch.yaml
images:
- name: controller
  newName: quay.io/mmahmoud/ingress-node-firewall-controller
  newTag: bpfman-latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
